-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "qtdClicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qtdLogins" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ultimaAtualizacao" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "ultimoLogin" TIMESTAMP(3);
